apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: airflow
    meta.helm.sh/release-namespace: airflow
  creationTimestamp: "2023-05-10T06:42:54Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: airflow-1.6.0
    component: statsd
    heritage: Helm
    release: airflow
    tier: airflow
  name: airflow-statsd
  namespace: airflow
  resourceVersion: "243515"
  uid: e79887bf-b266-40aa-94e9-b93ce77c5c46
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: statsd
      release: airflow
      tier: airflow
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: statsd
        release: airflow
        tier: airflow
    spec:
      affinity: {}
      containers:
      - args:
        - --statsd.mapping-config=/etc/statsd-exporter/mappings.yml
        image: apache/airflow:airflow-statsd-exporter-2021.04.28-v0.17.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9102
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: statsd
        ports:
        - containerPort: 9125
          name: statsd-ingest
          protocol: UDP
        - containerPort: 9102
          name: statsd-scrape
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9102
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 65534
      serviceAccount: airflow-statsd
      serviceAccountName: airflow-statsd
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2023-05-10T06:42:54Z"
    lastUpdateTime: "2023-05-10T06:43:14Z"
    message: ReplicaSet "airflow-statsd-7586f9998" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-05-10T06:52:55Z"
    lastUpdateTime: "2023-05-10T06:52:55Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1